#!/data/data/com.termux/files/usr/bin/python3
import os
import tarfile 
import colorama
from colorama import Fore,Back,Style
os.system('clear')
text = """
                        `:oDFo:`
                     ./ymM0dayMmy/.
                  -+dHJ5aGFyZGVyIQ==+-
              `:sm⏣~~Destroy.No.Data~~s:`
         -+h2~~Maintain.No.Persistence~~h+-
     `:odNo2~~Above.All.Else.Do.No.Harm~~Ndo:`
  ./etc/shadow.0days-Data'%20OR%201=1--.No.0MN8'/.
-++SecKCoin++e.AMd`       `.-://///+hbove.913.ElsMNh+-
-~/.ssh/id_rsa.Des-                  `htN01UserWroteMe!-
:dopeAW.No<nano>o                     :is:TЯiKC.sudo-.A:   
:we're.all.alike'`                     The.PFYroy.No.D7:  
:PLACEDRINKHERE!:                      yxp_cmdshell.Ab0:      OPTIONS
:msf>exploit -j.                       :Ns.BOB&ALICEes7:
:---srwxrwx:-.`                        `MS146.52.No.Per:
:<script>.Ac816/                        sENbove3101.404:   [1] INSTALL 
:NT_AUTHORITY.Do                        `T:/shSYSTEM-.N:   [2] UNINSTALL
:09.14.2011.raid                       /STFU|wall.No.Pr:   [3] REPAIR
:hevnsntSurb025N.                      dNVRGOING2GIVUUP:
:#OUTHOUSE-  -s:                       /corykennedyData:
:$nmap -oS                              SSo.6178306Ence:
:Awsm.da:                            /shMTl#beats3o.No.:
:Ring0:                             `dDestRoyREXKC3ta/M:
:23d:                               sSETEC.ASTRONOMYist:
 /-                               .ence.N:(){ :|: & };:
"""
msft = """
░█▄█░█▀▀░▀█▀░█▀█░█▀▀░█▀█░█░░░█▀█░▀█▀░▀█▀                 
░█░█░█▀▀░░█░░█▀█░▀▀█░█▀▀░█░░░█░█░░█░░░█░  INSTALLER   
░▀░▀░▀▀▀░░▀░░▀░▀░▀▀▀░▀░░░▀▀▀░▀▀▀░▀▀▀░░▀  
"""
h1 = '======================================================================'
def heading(h11):
	print(Fore.BLUE+ "["+ Fore.RED + "*" + Fore.BLUE + "]" , Fore.YELLOW + Style.BRIGHT + h11 )
	print(Fore.GREEN)
def sys(command):
	os.system(command)
def gr():
	print(Fore.GREEN)
class msf():
	def update_program():
		sys('rm $PREFIX/bin/msf_ins')
		sys('rm $PREFIX/bin/ins.sh')
		sys('rm $PREFIX/bin/ins.sh')
		sys('cd $PREFIX/bin/')
		sys('wget https://raw.githubusercontent.com/T-Dynamos/Metasploit/main/msf_ins')
		sys('wget https://raw.githubusercontent.com/T-Dynamos/Metasploit/main/ins.sh')
		sys('wget https://raw.githubusercontent.com/T-Dynamos/Metasploit/main/ruby.sh')
		sys('cd $HOME')
		sys('clear')
		return msf.main
	def install():
		gr()
		heading("Attempting to Install Metasploit...")
		print()
		gr()
		heading(" FIXNG RUBY... ")
		os.system('sh $PREFIX/bin/ruby.sh')
		print()
		gr()
		heading(" INSTALLING PACAKAGES...")
		file1=os.path.isfile('/data/data/com.termux/files/usr/opt/metasploit-framework/msfconsole')
		if file1 == True:
			print("The msf already exists")
			print("Return Repair")
			return msf.main
		os.system('pkg install -y python autoconf bison clang coreutils curl findutils apr apr-util postgresql openssl readline libffi libgmp libpcap libsqlite libgrpc libtool libxml2 libxslt ncurses make ncurses-utils ncurses git wget unzip zip tar termux-tools termux-elf-cleaner pkg-config git')
		os.system('python3 -m pip install requests')
		print()
		heading("DOWNLOADING METASPLOIT...")
		os.system('cd /data/data/com.termux/files/usr')
		os.system('mkdir /data/data/com.termux/files/usr/opt')
		sys('HOME=/data/data/com.termux/files/home')
		os.chdir('/data/data/com.termux/files/usr/opt')
		a = os.path.isfile('/data/data/com.termux/files/home/6.0.52.tar.gz')
		if a == True:
			print("File Already Exists")
		if a == False:
			sys('git clone https://github.com/rapid7/metasploit-framework.git')
		sys('rm 6.0.52.tar.gz')
		print()
		heading("Downloading Done...")
		print()
		gr()
		heading("INSTALLING METASPLOIT...")
		sys('sh $PREFIX/bin/ins.sh')
		print()
		heading(" INSTALLATION SUCCESSFULL...")
		heading(" UPDATING ")
		os.system('msfupdate')
		exit()
	def uninstall():
		k=input(" Are you serious (Y/N) = ")	
		if k == 'y':
			print("OK")
			os.system('rm -rf $PREFIX/opt/metasploit-framework/')
			print("DONE !!")
		if k == 'n':
				print(" IDIOt")
				os.system('clear')
				return msf.main
		else:
			return msf.main()
				
	def main():
		os.system('clear')
		print(Fore.MAGENTA +Style.BRIGHT + text)
		print(Fore.RED , msft)
		print()
		print(Fore.CYAN , h1)
		print()
		a = input( " [*] Your Choice = ")
		print()
		print(h1)
		if a =='1':
		    msf.install()
		if a == '2':
			msf.uninstall()
		if a == '3':
			print("Reinstalling Metasploit Framework ... ")
			return msf.uninstall
			return msf.install
			heading(" REPAIR COMPLETE")

			exit()
		if a == 'a':
			msf.update_program()
msf.main()                                       
