#!/data/data/com.termux/files/usr/bin/python3
import os
import time
import colorama
from colorama import Fore,Back,Style
os.system('clear')
disc = """ 

================= TERMUX METASPLOIT DISCLAIMER =============

Metasploit Framework and its 
dependencies are being sideloaded.  That solution makes
package potentially 
unstable.  We do not guarantee compatibility of installed
Ruby modules with our
 Ruby interpreter version and general compatibility with
Android OS.
	
It is highly recommended to have a stable Internet connection 
and clean Termux environment with up-to-date packages before
installing Metasploit.
	
Package is intended to be used by experienced users. 
 Do not ask Termux developers about how
 to use Metasploit, we won't do so and generally are not helping
anyone with topics related
to hacking.

Installation will be started in 10 seconds, thanks for attention

 ===============================================================
	 
"""

text = """
░█▄█░█▀▀░▀█▀░█▀█░█▀▀░█▀█░█░░░█▀█░▀█▀░▀█▀                 
░█░█░█▀▀░░█░░█▀█░▀▀█░█▀▀░█░░░█░█░░█░░░█░  
░▀░▀░▀▀▀░░▀░░▀░▀░▀▀▀░▀░░░▀▀▀░▀▀▀░▀▀▀░░▀  
Coders = T-Dynamos | Ansh Dadwal | Thanks = @BaapG"""
h1 = '==============================='
def heading(h11):
	print(Fore.BLUE+ "["+ Fore.RED + "*" + Fore.BLUE + "]" , Fore.YELLOW + Style.BRIGHT + h11 )
	print(Fore.GREEN)
def sys(command):
	os.system(command)
def gr():
	print(Fore.GREEN)
class msf():
	def update_program():
		sys('rm $PREFIX/bin/msf_ins')
		sys('rm $PREFIX/bin/ins.sh')
		sys('rm $PREFIX/bin/ins.sh')
		sys('cd $PREFIX/bin/')
		sys('wget https://raw.githubusercontent.com/T-Dynamos/Metasploit/main/msf_ins')
		sys('wget https://raw.githubusercontent.com/T-Dynamos/Metasploit/main/ins.sh')
		sys('wget https://raw.githubusercontent.com/T-Dynamos/Metasploit/main/ruby.sh')
		sys('cd $HOME')
		sys('clear')
		return msf.main
	def install():
		gr()
		heading("Attempting to Install Metasploit...")
		print()
		str12 = disc.center(20,'ㅤ')
		print(str12)
		time.sleep(10)
		print()
		gr()
		heading(" FIXNG RUBY... ")
		os.system('sh $PREFIX/bin/ruby.sh')
		print()
		gr()
		heading(" INSTALLING PACAKAGES...")
		os.system('pkg install -y python autoconf bison clang coreutils curl findutils apr apr-util postgresql openssl readline libffi libgmp libpcap libsqlite libgrpc libtool libxml2 libxslt ncurses make ncurses-utils ncurses git wget unzip zip tar termux-tools termux-elf-cleaner pkg-config git')
		os.system('python3 -m pip install requests')
		print()
		heading("DOWNLOADING METASPLOIT...")
		file1=os.path.isfile('/data/data/com.termux/files/usr/opt/metasploit-framework/msfconsole')
		if file1 == True:
			print("The Metasploit already exists")
		os.system('cd /data/data/com.termux/files/usr')
		os.system('mkdir /data/data/com.termux/files/usr/opt > /dev/null 2&>1')
		sys('HOME=/data/data/com.termux/files/home')
		os.chdir('/data/data/com.termux/files/usr/opt')
		a = os.path.isfile('/data/data/com.termux/files/home/6.0.52.tar.gz')
		if a == True:
			print("File Already Exists")
		if a == False:
			sys('git clone https://github.com/rapid7/metasploit-framework.git')
			msfpath = os.path.isfile('/data/data/com.termux/files/usr/opt/metasploit-framework/msfconsole')
			if msfpath == False:
				print()
				heading(Fore.RED + "DOWNLOAD   FAILED !! ")
				exit()
			if msfpath == True:
				pass
		print()
		heading("Downloading Done...")
		print()
		gr()
		heading("INSTALLING METASPLOIT...")
		sys('sh $PREFIX/bin/ins.sh')
		print()
		heading(" INSTALLATION SUCCESSFULL...")
		heading(" UPDATING ")
		os.system('msfconsole')
		heading(Fore.RED + 'Installation Failed :( ')
	def uninstall():
		k=input(" Are you serious (Y/N) = ")	
		if k == 'y':
			print("OK")
			os.system('rm -rf $PREFIX/opt/metasploit-framework/')
			os.remove('/data/data/com.termux/files/usr/etc/apt/sources.list.d/gushmazuko.list')
			os.system('apt remove ruby')
			os.system('apt install ruby')
			print("DONE !!")
			exit()
		if k == 'n':
				print(" IDIOt")
				os.system('clear')
				return msf.main
		else:
			return msf.main()
				
	def main():
		os.system('clear')
		print(Fore.MAGENTA +Style.BRIGHT + text)
		print(Fore.GREEN)
		print(h1)
		print()
		print(Fore.CYAN + "Choose Any Option" + Fore.GREEN)
		print()
		print("[1] Install")
		print("[2] Uninstall")
		print("[3] Repair")
		print()
		print(h1)
		print(Fore.CYAN)
		a = input( " [*] Your Choice = ")
		print()
		print(h1)
		if a =='1':
		    msf.install()
		if a == '2':
			msf.uninstall()
		if a == '3':
			heading("Reinstalling Metasploit Framework ... ")
			return msf.uninstall()
			return msf.install()
			heading(" REPAIR COMPLETE")
			exit()
		if a == 'a':
			msf.update_program()
msf.main()                                